name: Coder Habits
description: Coding as a hobby
meta_description: "Coder Habits, coding as a hobby"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://coderhabits.com'
google_analytics: 'UA-59909394-1'

# Details for the RSS feed generator
url:            'http://coderhabits.com'
author:         'Lenin Yee'
